added generation of nserror data enums. it differs from generic by: - inherits NSErrorCode - contains inner NSError subclass that automatically register error domain in NSError (e.g. no need to create standalone subclass)
to mark enum to be NSErrorCode enum use nserror: parameter I’m yaml,  e.g.
    GKErrorCode: { nserror: true }
    GKSessionError: { nserror: true, suffix: Error }
    GKVoiceChatServiceError: { nserror: true, suffix: Error }